name = "glassroot-api"
main = "src/index.ts"
compatibility_date = "2024-08-01"

[vars]
# Set this to a specific origin (e.g., https://staging.example.com) per env; defaults to "*" in dev
CORS_ORIGIN = "*"

[[d1_databases]]
binding = "DB"
database_name = "glassroot"
database_id = "${D1_DATABASE_ID}"

[[vectorize]]
binding = "VECTORS"
index_name = "glassroot-vectors"
index_id = "${VECTORIZE_INDEX_ID}"

[ai]
binding = "AI"

[env.staging]
[env.staging.vars]
CORS_ORIGIN = "https://staging.example.com"

[env.production]
[env.production.vars]
CORS_ORIGIN = "https://example.com"
